### ISSUE TITLE
Issues with content width and height

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/stunning-start-page#1]
I'm still working on this exercise but struggling with couple things mentioned below (temporarily put coloured border around certain elements for clarity): [https://c-g-g.github.io/stunning-start-page/](url)

1- `<div>` element inside `<li>` (highlighted with yellow border that contains the icon image and strong element)… why is it wider than its content (so much space on the left side of the icon) and what can I do to get it (its background) to be the exact width as its content? 

Also, I gave that icon image a width of 8% but am not sure if this is the right way to do it and whether there is a better way.

2- `<li>` element inside `<section>` `<ul>` (highlighted with red border) is taller than it should be… trying to understand why and the best way to match the screenshot (min-height? max-height? should this be applied to image or li or both? or something else? a more organic way such as using a flex property?). (I should probably go back and watch the video(s) again; just couldn’t remember in which video this topic was covered.)

@thomasjbradley

**Comment by thomasjbradley** [comment]
This might solve both problems: I used `display: grid` on the `<li>` instead of `display: flex`. That way I can use areas to control the position of the image, the `<h3>` and the little description.

**Comment by C-G-G** [comment]
I'm trying to figure out how you use `display: grid` on the `<li>`... one column (auto) and three rows? For the rows, how much space do you allocate, 1fr auto 1fr? For the little description, do you use flex?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, 1 column with 3 rows. I didn’t specify the row heights, so I guess they are all `auto`. This is how I did it:

```css
section li {
  display: grid;
  grid-template-columns: 1fr;
  grid-template-areas:
    "top"
    "middle"
    "bottom";
}
```

But with the one trick that the image spans all 3 rows, like: `grid-row: 1 / -1;`

<img width="382" alt="Screen Shot 2021-03-19 at 1 14 04 PM" src="https://user-images.githubusercontent.com/105192/111818034-1bb16200-88b5-11eb-8ead-89b751ac6972.png">

**Comment by C-G-G** [comment]
@thomasjbradley - thanks a lot, I’m SO close to completing this project but…

1- Still struggling with `<div>` element inside `<li>`(please see point #1 above);
 
2- background-color (transparency) for `<h3>`… all colours in this project are provided in HEX value so I try to add opacity separately but then it is applied not only to background-color but also to h3. In order to apply opacity to background-color alone (and not h3), do I need to convert these HEX values to RGBA or HSLA format? There should be another/ easier way, no?

3- I don’t want to take too much of your time but am curious about your approach for `<header>`… to layout the header elements (`<h1>` and the two elements within `<div>`), I used almost all methods (grid, flex and positioning)…. Wondering if what I did and how I did it is correct, and whether there is a better, more efficient, simpler way? Curious about how you did it, your solution :) (Responsiveness and media queries are covered in upcoming weeks so we’re not taking those into account for now I’m guessing)

4 - One last small issue: you may see that the left side of `<header>` (the gap on left side of “Help Me” button - highlighted with blue border) is not properly aligned with the rest of the page… For life of me, I cannot figure out where that gap is coming from and how to get rid of it (tried everything including margin-left: 0 to all elements within header there)

https://c-g-g.github.io/stunning-start-page/

**Comment by thomasjbradley** [comment]
**1.** It’s the icon image within the `<div>` that’s causing the problem. Try setting its `width` **and** `height` to a more fixed measurement like `1em` or something.

**2.** Converting to RGBA or HSLA is a good way to do it. Depending on browser support you can also do alpha on HEX numbers now: https://caniuse.com/css-rrggbbaa
(Though I don’t know if Markbot is updated enough to see this feature.)

**3.** I didn’t use `position` to make the `<header>` layout work: only Grid & Flexbox. Your grid is good, but I then made the `<nav>` stretch across all columns in the grid and used `space-between` to push the buttons away to the edges.

**4.** Caused by `padding` on the left of the `<ul>`

**Comment by C-G-G** [comment]
**1.** I set the icon image `width` **and** `height` to `1em` then to `2em` but neither worked :(

**2.** Yes, I converted HEX to RGBA and all good now :)

**3.** Please see below. 

**4.** Hmmm, I have `padding` only on `<nav>` `<ul>` `<li>`, and removing it doesn’t help with the issue. 

Because I’m also curious about your solution for point 3 (still not clear how you managed to stretch `<nav>` across all columns and centered `<h1>` at same time), I’m wondering if you could share your code just for `<header>` (privately if public would be an issue), which would really help me with both 3 and 4. Thanks SO much!

@thomasjbradley

**Comment by thomasjbradley** [comment]
1. Keep the width & height. Add `justify-self: end` to the `<div>`

4. The `<ul>` tag in the navigation has padding on it’s left by default—provided by the browser. You need to overwrite it.

```css
nav ul {
  padding-left: 0;
}
```

3. Here’s simplified code for the header to help understanding:

```css
header {
  display: grid;
  grid-template-columns: auto 10rem auto;
  grid-template-rows: auto 1.5rem;
  grid-template-areas:
    "left center right"
    ".    center     .";
}

header h1 {
  grid-area: center;
  z-index: 1;
}

nav {
  grid-column: 1 / -1; /* HERE: Stretch from column line 1 to column line -1 (the last) */
  grid-row: 1;
}
```

**Comment by C-G-G** [comment]
All good now :) Markbot is (almost) happy... says that it is visually too different from the screenshot but I believe it's a glitch because what it shows to me is not what I see on the browser. Otherwise, no errors or complaints :) Thanks again SO much for your time and patience!
